version: '3'

services:
  # Configuration for Hub+Proxy
  jupyterhub:
    image: docker.io/bigsidhu/jupyterhub                # Build the container from this folder.
    container_name: jupyterhub   # The service will use this container name.
    volumes:                         # Give access to Docker socket.
      - /var/run/docker.sock:/var/run/docker.sock
    environment:                     # Env variables passed to the Hub process.
      DOCKER_JUPYTER_IMAGE: docker.io/bigsidhu/jupyter-notebook:latest
      DOCKER_NETWORK_NAME: jupyterhub_default
      HUB_IP: jupyterhub
    labels:                          # Traefik configuration.
      - "traefik.enable=true"
      - "traefik.http.routers.jupyterhub.rule=Host(`jupyter.dev.lan`)"
      - "traefik.http.routers.jupyterhub.entrypoints=web"
    restart: unless-stopped

  # Configuration for reverse proxy
  reverse-proxy:
    image: traefik
    container_name: "traefik"
    depends_on:
      - jupyterhub
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
